# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/iarigby"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://mastodon.social/@bitscomplicated"

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "threads"
name = "Threads"
url = "https://www.threads.net/@bitscomplicated_"

[[social.params]]
icon = "brand-threads"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/bitscomplicated_/"

[[social.params]]
icon = "brand-instagram"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://at.linkedin.com/in/ia-mgvdliashvili-0b459768"

[[social.params]]
icon = "brand-linkedin"